<?php

$labels = array();
$labels['use_2fa'] = 'Use two-factor authentication';
$labels['otp'] = 'One-time password';
$labels['enter_otp_from_your_token'] = 'Enter one-time password from your token';
$labels['to_log_in'] = 'Log In';
$labels['protectimus_otp_authentication'] = 'Protectimus one-time password authentication';
$labels['self_service_url'] = 'Self-service URL';
$labels['challenge'] = 'Challenge';
$labels['invalid_otp'] = 'Invalid one-time password';

?>