<?php

$labels = array();
$labels['use_2fa'] = 'Использовать двухфакторную аутентификацию';
$labels['otp'] = 'Одноразовый пароль';
$labels['enter_otp_from_your_token'] = 'Введите одноразовый пароль из Вашего токена';
$labels['to_log_in'] = 'Войти';
$labels['protectimus_otp_authentication'] = 'Protectimus aутентификация с помощью одноразового пароля';
$labels['self_service_url'] = 'Адрес страницы самооблуживания';
$labels['challenge'] = 'Ваш вопрос';
$labels['invalid_otp'] = 'Неверный одноразовый пароль';

?>